# Generated by Django 4.1.7 on 2023-03-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experience', models.CharField(choices=[('junior', 'Junior'), ('mid_level', 'Mid Level'), ('senior', 'Senior')], max_length=20)),
                ('type', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanprime.offer')),
            ],
        ),
    ]
