# Generated by Django 4.1.7 on 2023-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='competences',
            field=models.ManyToManyField(blank=True, to='fanprime.competence'),
        ),
    ]
