# Generated by Django 4.1.7 on 2023-03-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprime', '0002_remove_competence_offer_offer_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='competences',
            field=models.ManyToManyField(to='fanprime.competence'),
        ),
    ]
