# Generated by Django 4.1.7 on 2023-03-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprime', '0003_alter_offer_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='competences',
            field=models.ManyToManyField(related_name='competences', to='fanprime.competence'),
        ),
    ]
